version: '2'
services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  storage:
    image: 'ghcr.io/sooheon45/store-app/storage:v0-0-77'
    ports:
      - '8080:8080'
    volumes:
      - './path/to/storage/config:/app/config'
  factory:
    image: 'ghcr.io/sooheon45/factory/factory:v0-0-9'
    ports:
      - '8080:8080'
    volumes:
      - './path/to/factory/config:/app/config'
  store:
    image: 'ghcr.io/sooheon45/factory/store:v0-0-9'
    ports:
      - '8080:8080'
    volumes:
      - './path/to/store/config:/app/config'
